name: Publish Release to Maven Central

concurrency:
  group: release-${{ github.repository }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version (e.g. 0.19)"
        required: true
      nextVersion:
        description: "Next snapshot version (e.g. 0.20-SNAPSHOT)"
        required: true

permissions:
  contents: write
  pull-requests: write


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: 'true'

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Configure Maven Central credentials
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>central</id>
                <username>${{ secrets.MAVEN_CENTRAL_TOKEN_USER }}</username>
                <password>${{ secrets.MAVEN_CENTRAL_TOKEN_PASS }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Prepare Release Version
        run: |
          mvn -B versions:set -DnewVersion=${{ github.event.inputs.releaseVersion }}
          mvn -B versions:commit

      - name: Commit Release Version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Release ${{ github.event.inputs.releaseVersion }}"

      - name: Tag Release
        run: git tag ${{ github.event.inputs.releaseVersion }}

      - name: Deploy Release to Maven Central
        run: mvn -B -Pproduction-release deploy

      - name: Prepare Next Development Version
        run: |
          mvn -B versions:set -DnewVersion=${{ github.event.inputs.nextVersion }}
          mvn -B versions:commit

      - name: Commit Next Snapshot
        run: |
          git commit -am "Start ${{ github.event.inputs.nextVersion }}"

      - name: Push Changes
        run: |
          git push --follow-tags
